spring:
  datasource:
    url: jdbc:mysql://mysql-19372a1a-onemorerep24x7-bee5.c.aivencloud.com:24758/plans?createDatabaseIfNotExist=true
    username: avnadmin
    password: AVNS_rflvDobFJTFAwmgbo8u
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true # Set to true to see generated SQL queries
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  instance:
    host: localhost
  client:
    service-url:
      defaultZone: http://3.111.235.72:8761/eureka

server:
  port: 8082

management:
  tracing:
    sampling:
      probability: 1.0
